package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 5:41:07 PM by Hibernate Tools 5.4.20.Final


import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Messagecandidature generated by hbm2java
 */
@Entity
@Table(name="messagecandidature"
    ,schema="public"
)
public class Messagecandidature implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


    private int id;
    private Candidature candidature;
    private Offreemploi offreemploi;
    private Date dateenvoi;
    private String corpsmessage;

    public Messagecandidature() {
    }

	
    public Messagecandidature(int id, Date dateenvoi, String corpsmessage) {
        this.id = id;
        this.dateenvoi = dateenvoi;
        this.corpsmessage = corpsmessage;
    }
    public Messagecandidature(int id, Candidature candidature, Offreemploi offreemploi, Date dateenvoi, String corpsmessage) {
       this.id = id;
       this.candidature = candidature;
       this.offreemploi = offreemploi;
       this.dateenvoi = dateenvoi;
       this.corpsmessage = corpsmessage;
    }
   
    @Id
    @SequenceGenerator(name="messagecandidature_ID_GENERATOR", sequenceName="messagecandidature_id_seq", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="messagecandidature_ID_GENERATOR") 
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_candidature")
    public Candidature getCandidature() {
        return this.candidature;
    }
    
    public void setCandidature(Candidature candidature) {
        this.candidature = candidature;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_offreemploi")
    public Offreemploi getOffreemploi() {
        return this.offreemploi;
    }
    
    public void setOffreemploi(Offreemploi offreemploi) {
        this.offreemploi = offreemploi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateenvoi", nullable=false, length=13)
    public Date getDateenvoi() {
        return this.dateenvoi;
    }
    
    public void setDateenvoi(Date dateenvoi) {
        this.dateenvoi = dateenvoi;
    }

    
    @Column(name="corpsmessage", nullable=false)
    public String getCorpsmessage() {
        return this.corpsmessage;
    }
    
    public void setCorpsmessage(String corpsmessage) {
        this.corpsmessage = corpsmessage;
    }




}


