package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 5:41:07 PM by Hibernate Tools 5.4.20.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

/**
 * Niveauqualification generated by hbm2java
 */
@Entity
@Table(name="niveauqualification"
    ,schema="public"
)
public class Niveauqualification  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    
  
     private int id;
     private String intitule;
     private Set<Candidature> candidatures = new HashSet<Candidature>(0);
     private Set<Offreemploi> offreemplois = new HashSet<Offreemploi>(0);

    public Niveauqualification() {
    }

	
    public Niveauqualification(int id, String intitule) {
        this.id = id;
        this.intitule = intitule;
    }
    public Niveauqualification(int id, String intitule, Set<Candidature> candidatures, Set<Offreemploi> offreemplois) {
       this.id = id;
       this.intitule = intitule;
       this.candidatures = candidatures;
       this.offreemplois = offreemplois;
    }
   
    @Id 
    @SequenceGenerator(name="niveauqualification_ID_GENERATOR", sequenceName="niveauqualification_id_seq", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="niveauqualification_ID_GENERATOR")
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="intitule", nullable=false, length=50)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="niveauqualification")
    public Set<Candidature> getCandidatures() {
        return this.candidatures;
    }
    
    public void setCandidatures(Set<Candidature> candidatures) {
        this.candidatures = candidatures;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="niveauqualification")
    public Set<Offreemploi> getOffreemplois() {
        return this.offreemplois;
    }
    
    public void setOffreemplois(Set<Offreemploi> offreemplois) {
        this.offreemplois = offreemplois;
    }




}


