package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 5:41:07 PM by Hibernate Tools 5.4.20.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Offreemploi generated by hbm2java
 */
@Entity
@Table(name="offreemploi"
    ,schema="public"
)
public class Offreemploi  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


    private int id;
    private Niveauqualification niveauqualification;
    private String title;
    private String descriptifmission;
    private String profilrecherche;
    private Date datedepot;
    private Entreprise entreprise;
    private Set<Messagecandidature> messagecandidatures = new HashSet<Messagecandidature>(0);
    private Set<Messageoffredemploi> messageoffredemplois = new HashSet<Messageoffredemploi>(0);
    private Set<Secteuractivite> secteuractivites = new HashSet<Secteuractivite>(0);

    public Offreemploi() {
    }

	
    public Offreemploi(int id, String title, String descriptifmission, String profilrecherche, Date datedepot, Entreprise ent, Set<Secteuractivite> secteuractivites) {
        this.id = id;
        this.title = title;
        this.descriptifmission = descriptifmission;
        this.profilrecherche = profilrecherche;
        this.datedepot = datedepot;
        this.entreprise = ent;
        this.secteuractivites = secteuractivites;
    }
    public Offreemploi(int id, Niveauqualification niveauqualification, String title, String descriptifmission, String profilrecherche, Date datedepot, Entreprise entreprise, Set<Messagecandidature> messagecandidatures, Set<Messageoffredemploi> messageoffredemplois, Set<Secteuractivite> secteuractivites) {
       this.id = id;
       this.niveauqualification = niveauqualification;
       this.title = title;
       this.descriptifmission = descriptifmission;
       this.profilrecherche = profilrecherche;
       this.datedepot = datedepot;
       this.entreprise = entreprise;
       this.messagecandidatures = messagecandidatures;
       this.messageoffredemplois = messageoffredemplois;
       this.secteuractivites = secteuractivites;
    }
   

    @Id 
    @SequenceGenerator(name="offreemploi_ID_GENERATOR", sequenceName="offreemploi_id_seq", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="offreemploi_ID_GENERATOR")
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_niveauqualification")
    public Niveauqualification getNiveauqualification() {
        return this.niveauqualification;
    }
    
    public void setNiveauqualification(Niveauqualification niveauqualification) {
        this.niveauqualification = niveauqualification;
    }

    
    @Column(name="title", nullable=false, length=50)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="descriptifmission", nullable=false)
    public String getDescriptifmission() {
        return this.descriptifmission;
    }
    
    public void setDescriptifmission(String descriptifmission) {
        this.descriptifmission = descriptifmission;
    }

    
    @Column(name="profilrecherche", nullable=false)
    public String getProfilrecherche() {
        return this.profilrecherche;
    }
    
    public void setProfilrecherche(String profilrecherche) {
        this.profilrecherche = profilrecherche;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datedepot", nullable=false, length=13)
    public Date getDatedepot() {
        return this.datedepot;
    }
    
    public void setDatedepot(Date datedepot) {
        this.datedepot = datedepot;
    }

    //@Column(name="id_entreprise")
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_entreprise", nullable=false)
    public Entreprise getEntreprise() {
        return this.entreprise;
    }
    
    public void setEntreprise(Entreprise entreprise) {
        this.entreprise = entreprise;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="offreemploi")
    public Set<Messagecandidature> getMessagecandidatures() {
        return this.messagecandidatures;
    }
    
    public void setMessagecandidatures(Set<Messagecandidature> messagecandidatures) {
        this.messagecandidatures = messagecandidatures;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="offreemploi")
    public Set<Messageoffredemploi> getMessageoffredemplois() {
        return this.messageoffredemplois;
    }
    
    public void setMessageoffredemplois(Set<Messageoffredemploi> messageoffredemplois) {
        this.messageoffredemplois = messageoffredemplois;
    }

    @ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="offresecteur", schema="public", joinColumns = { 
        @JoinColumn(name="id_offreemploi", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_secteuractivite", nullable=false, updatable=false) })
    public Set<Secteuractivite> getSecteuractivites() {
        return this.secteuractivites;
    }
    
    public void setSecteuractivites(Set<Secteuractivite> secteuractivites) {
        this.secteuractivites = secteuractivites;
    }




}


